services:
  - type: web
    name: telegram-archive-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
